{% set name = "openfermion" %}
{% set version = "0.11.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/openfermion-{{ version }}.tar.gz
  sha256: 2aede7cf2e5f7be4c0016c9b542c27505644f8ecb9411c653dc89a5cd746f84c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - h5py >=2.8
    - networkx
    - numpy >=1.11.0
    - pubchempy
    - python >=3.6
    - requests ~=2.18
    - scipy >=1.1.0

test:
  imports:
    - openfermion
    - openfermion.data
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://quantumai.google/openfermion
  summary: The electronic structure package for quantum computers.
  license: Apache-2.0 AND BSD-3-Clause
  license_file:
    - LICENSE
    - NOTICE
  dev_url: https://github.com/quantumlib/OpenFermion

extra:
  recipe-maintainers:
    - BastianZim
