{% set name = "openfermion" %}
{% set version = "1.7.1" %}
{% set python_min = "3.10" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/openfermion-{{ version }}.tar.gz
  sha256: 717f4b969a1fd1df24f11bd462b485d317f257bdd91cef32ced23d276cc83f70

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - cirq-core >=1.4.1
    - deprecation
    - h5py >=3.10.0
    - networkx
    - numpy >=1.26
    - pubchempy
    - python >={{ python_min }}
    - requests >=2.32.2,<2.33.dev0
    - scipy >=1.15,<2.dev0
    - sympy

test:
  imports:
    - openfermion
    - openfermion.chem
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://quantumai.google/openfermion
  summary: The electronic structure package for quantum computers.
  license: Apache-2.0 AND BSD-3-Clause
  license_file:
    - LICENSE
    - NOTICE
  dev_url: https://github.com/quantumlib/OpenFermion

extra:
  recipe-maintainers:
    - BastianZim
